/**
 * Disposable / temporary email domain blocklist.
 *
 * A bundled subset of the most common throwaway email providers.
 * Full list maintained at: https://github.com/disposable-email-domains
 *
 * Usage: isDisposableDomain("mailinator.com") → true
 *
 * When to update: periodically pull new entries from the GitHub list above
 * and add them here. For a live project, replace this with an async fetch
 * backed by a short-lived cache.
 */

const DISPOSABLE_DOMAINS = new Set<string>([
  // ── High-volume throwaway services ──────────────────────────────────────
  "mailinator.com",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamail.info",
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.org",
  "throwam.com",
  "throwam.net",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "tempmail.com",
  "temp-mail.org",
  "temp-mail.io",
  "trashmail.com",
  "trashmail.at",
  "trashmail.io",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "sharklasers.com",
  "guerrillamailblock.com",
  "grr.la",
  "spam4.me",
  "spamgourmet.com",
  "spamgourmet.net",
  "spamgourmet.org",
  "mailnull.com",
  "spamherelots.com",
  "maildrop.cc",
  "dispostable.com",
  "fakeinbox.com",
  "mailnesia.com",
  "mailexpire.com",
  "filzmail.com",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "spamfree24.org",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "spamfree24.net",
  "jetable.fr.nf",
  "jetable.com",
  "nomail.xl.cx",
  "maileimer.de",
  "antispam24.de",
  "deadaddress.com",
  "spamoff.de",
  "emailsensei.com",
  "throwaway.email",
  "throwam.com",
  "spamgap.com",
  "mohmal.com",
  "meltmail.com",
  "klzlk.com",
  "anonmails.de",
  "anonymbox.com",
  "notmailinator.com",
  "bspamfree.org",
  "frapmail.com",
  "oopi.org",
  "ifnull.org",
  "mailnew.com",
  "mytempemail.com",
  "boximail.com",
  "getairmail.com",
  "incognitomail.org",
  "mailtemp.org",
  "mailtemp.info",
  "mailtemp.net",
  "spamtemp.net",
  "fakeemailgenerator.com",
  "spoofmail.de",
  "tempinbox.com",
  "mailmetrash.com",
  "haltospam.com",
  "crazespam.com",
  "putthisinyourspamdatabase.com",
  "thisisnotmyrealemail.com",
  "chacuo.net",
  "mailsac.com",
  "tempr.email",
  "tempsky.com",
  "tmailinator.com",
  "drdrb.com",
  "anonaddy.com",
  "simplelogin.io",
  "duckdao.io",
  "spamgourmet.com",
  "binkmail.com",
  "bob.email",
  "getnada.com",
  "owlpic.com",
  "superrito.com",
  "ieatspam.eu",
  "ieatspam.info",
  "despam.it",
  "orangatango.com",
  "spaml.de",
  "spaml.com",
  "spaml.net",
  "mmmmail.com",
  "dingbone.com",
  "fudgerub.com",
  "lookugly.com",
  "dontsendmespam.de",
  "nomail.nodns.xyz",
  "inbox.si",
  "spamhereplease.com",
  "deadspam.com",
  "fakemailgenerator.com",
  "nospam4.us",
]);

/**
 * Check whether a domain is a known disposable / temporary email service.
 *
 * @param domain  e.g. "mailinator.com" — pass the domain only, not full email
 */
export function isDisposableDomain(domain: string): boolean {
  return DISPOSABLE_DOMAINS.has(domain.toLowerCase().trim());
}
